
DROP SEQUENCE Sequence_COMPANY;

DROP SEQUENCE Sequence_DEPT;

DROP SEQUENCE Sequence_FIELD;

DROP SEQUENCE Sequence_INFO;

DROP SEQUENCE Sequence_JOBSEEKER;

DROP SEQUENCE Sequence_JS_SCRAP;

DROP SEQUENCE Sequence_MANAGER;

DROP SEQUENCE Sequence_MATCHING_JW;

DROP SEQUENCE Sequence_MATCHING_TW;

DROP SEQUENCE Sequence_SPEC;

DROP SEQUENCE Sequence_STATISTIC;

DROP SEQUENCE Sequence_T_SCRAP;

DROP SEQUENCE Sequence_TRUST;

DROP SEQUENCE Sequence_TURNOVER;

DROP SEQUENCE Sequence_WORKER;

ALTER TABLE SPEC
DROP CONSTRAINT R_96;

ALTER TABLE SPEC
DROP CONSTRAINT R_97;

ALTER TABLE SPEC
DROP CONSTRAINT R_98;

ALTER TABLE JS_SCRAP
DROP CONSTRAINT R_30;

ALTER TABLE JS_SCRAP
DROP CONSTRAINT R_31;

ALTER TABLE T_SCRAP
DROP CONSTRAINT R_34;

ALTER TABLE T_SCRAP
DROP CONSTRAINT R_1113;

ALTER TABLE STATISTIC
DROP CONSTRAINT R_83;

ALTER TABLE STATISTIC
DROP CONSTRAINT R_82;

ALTER TABLE TRUST
DROP CONSTRAINT R_80;

ALTER TABLE INFO
DROP CONSTRAINT R_76;

ALTER TABLE INFO
DROP CONSTRAINT R_77;

ALTER TABLE recommend_matching_tw
DROP CONSTRAINT R_99;

ALTER TABLE recommend_matching_tw
DROP CONSTRAINT R_100;

ALTER TABLE Preparation_for_Turnover
DROP CONSTRAINT R_19;

ALTER TABLE Preparation_for_Turnover
DROP CONSTRAINT R_54;

ALTER TABLE Preparation_for_Turnover
DROP CONSTRAINT R_86;

ALTER TABLE recommend_matching_jw
DROP CONSTRAINT R_101;

ALTER TABLE recommend_matching_jw
DROP CONSTRAINT R_102;

ALTER TABLE Job_Seeker
DROP CONSTRAINT R_88;

ALTER TABLE Worker
DROP CONSTRAINT R_20;

ALTER TABLE Worker
DROP CONSTRAINT R_55;

ALTER TABLE Worker
DROP CONSTRAINT R_92;

ALTER TABLE DEPARTMENT
DROP CONSTRAINT R_39;

ALTER TABLE DEPARTMENT
DROP CONSTRAINT R_37;

ALTER TABLE SPEC
DROP PRIMARY KEY CASCADE  DROP INDEX;

ALTER TABLE MANAGER
DROP PRIMARY KEY CASCADE  DROP INDEX;

ALTER TABLE JS_SCRAP
DROP PRIMARY KEY CASCADE  DROP INDEX;

ALTER TABLE T_SCRAP
DROP PRIMARY KEY CASCADE  DROP INDEX;

ALTER TABLE STATISTIC
DROP PRIMARY KEY CASCADE  DROP INDEX;

ALTER TABLE TRUST
DROP PRIMARY KEY CASCADE  DROP INDEX;

ALTER TABLE INFO
DROP PRIMARY KEY CASCADE  DROP INDEX;

ALTER TABLE recommend_matching_tw
DROP PRIMARY KEY CASCADE  DROP INDEX;

ALTER TABLE Preparation_for_Turnover
DROP PRIMARY KEY CASCADE  DROP INDEX;

ALTER TABLE recommend_matching_jw
DROP PRIMARY KEY CASCADE  DROP INDEX;

ALTER TABLE Job_Seeker
DROP PRIMARY KEY CASCADE  DROP INDEX;

ALTER TABLE Worker
DROP PRIMARY KEY CASCADE  DROP INDEX;

ALTER TABLE DEPARTMENT
DROP PRIMARY KEY CASCADE  DROP INDEX;

ALTER TABLE FIELD
DROP PRIMARY KEY CASCADE  DROP INDEX;

ALTER TABLE COMPANY
DROP PRIMARY KEY CASCADE  DROP INDEX;

DROP INDEX XPKSPEC;

DROP INDEX XIF1SPEC;

DROP INDEX XIF2SPEC;

DROP INDEX XIF3SPEC;

DROP TABLE SPEC CASCADE CONSTRAINTS PURGE;

DROP INDEX XPKADMINISTRATOR;

DROP TABLE MANAGER CASCADE CONSTRAINTS PURGE;

DROP INDEX XIF1SCRAP;

DROP INDEX XIF2SCRAP;

DROP INDEX XPKSCRAP_JS;

DROP TABLE JS_SCRAP CASCADE CONSTRAINTS PURGE;

DROP INDEX XIF2SCRAP;

DROP INDEX XIF1SCRAP;

DROP INDEX XPKSCRAP_T;

DROP TABLE T_SCRAP CASCADE CONSTRAINTS PURGE;

DROP INDEX XPKSTATISTIC;

DROP INDEX XIF2STATISTIC;

DROP INDEX XIF1STATISTIC;

DROP TABLE STATISTIC CASCADE CONSTRAINTS PURGE;

DROP INDEX XPKTRUST;

DROP INDEX XIF1TRUST;

DROP TABLE TRUST CASCADE CONSTRAINTS PURGE;

DROP INDEX XPKINFO;

DROP INDEX XIF1INFO;

DROP INDEX XIF2INFO;

DROP TABLE INFO CASCADE CONSTRAINTS PURGE;

DROP INDEX XPKrecommend_matching_tw;

DROP INDEX XIF1recommend_matching_tw;

DROP INDEX XIF2recommend_matching_tw;

DROP TABLE recommend_matching_tw CASCADE CONSTRAINTS PURGE;

DROP INDEX XPKPreparation_for_Turnover;

DROP INDEX XIF3Preparation_for_Turnover;

DROP INDEX XIF5Preparation_for_Turnover;

DROP INDEX XIF6Preparation_for_Turnover;

DROP TABLE Preparation_for_Turnover CASCADE CONSTRAINTS PURGE;

DROP INDEX XPKrecommend_matching_jw;

DROP INDEX XIF1recommend_matching_jw;

DROP INDEX XIF2recommend_matching_jw;

DROP TABLE recommend_matching_jw CASCADE CONSTRAINTS PURGE;

DROP INDEX XPKJob_Seeker;

DROP INDEX XIF2Job_Seeker;

DROP TABLE Job_Seeker CASCADE CONSTRAINTS PURGE;

DROP INDEX XPKWorker;

DROP INDEX XIF3Worker;

DROP INDEX XIF5Worker;

DROP INDEX XIF6Worker;

DROP TABLE Worker CASCADE CONSTRAINTS PURGE;

DROP INDEX XPKDEPARTMENT;

DROP INDEX XIF1DEPARTMENT;

DROP INDEX XIF2DEPARTMENT;

DROP TABLE DEPARTMENT CASCADE CONSTRAINTS PURGE;

DROP INDEX XPKFIELD;

DROP TABLE FIELD CASCADE CONSTRAINTS PURGE;

DROP INDEX XPKCOMPANY;

DROP TABLE COMPANY CASCADE CONSTRAINTS PURGE;

CREATE TABLE COMPANY
(
	C_NUM                NUMBER NOT NULL ,
	C_NAME               VARCHAR2(20) NULL ,
	ADDRESS              VARCHAR2(20) NULL 
);

ALTER TABLE COMPANY
	ADD CONSTRAINT  XPKCOMPANY PRIMARY KEY (C_NUM);

CREATE TABLE DEPARTMENT
(
	CFD_NUM              NUMBER NOT NULL ,
	CFD_NAME             VARCHAR2(20) NULL ,
	CF_NUM               NUMBER NOT NULL ,
	C_NUM                NUMBER NULL 
);

ALTER TABLE DEPARTMENT
	ADD CONSTRAINT  XPKDEPARTMENT PRIMARY KEY (CFD_NUM);

CREATE TABLE MANAGER
(
	MGR_NUM              NUMBER NOT NULL ,
	ID                   VARCHAR2(10) NULL ,
	PW                   VARCHAR2(15) NULL 
);

ALTER TABLE MANAGER
	ADD CONSTRAINT  XPKADMINISTRATOR PRIMARY KEY (MGR_NUM);

CREATE TABLE TRUST
(
	CFD_NUM              NUMBER NOT NULL ,
	T_NUM                VARCHAR2(18) NOT NULL ,
	ANNUAL_INCOME        VARCHAR2(18) NULL ,
	DEPARTMENT_MOOD      VARCHAR2(18) NULL ,
	JOB_SATISFACTION     VARCHAR2(18) NULL ,
	CAFETERIA            VARCHAR2(18) NULL ,
	TRAFFIC__CONVENIENCE VARCHAR2(18) NULL 
);

ALTER TABLE TRUST
	ADD CONSTRAINT  XPKTRUST PRIMARY KEY (T_NUM);

CREATE TABLE FIELD
(
	CF_NUM               NUMBER NOT NULL ,
	CF_NAME              VARCHAR(20) NULL 
);

ALTER TABLE FIELD
	ADD CONSTRAINT  XPKFIELD PRIMARY KEY (CF_NUM);

CREATE TABLE Job_Seeker
(
	JS_ID                NUMBER NOT NULL ,
	NAME                 VARCHAR2(20) NULL ,
	SCHOOL               VARCHAR2(20) NULL ,
	MAJOR                VARCHAR2(20) NULL ,
	personal_email       VARCHAR2(30) NULL ,
	pw                   VARCHAR(18) NULL ,
	CF_NUM               NUMBER NULL ,
	MATCHING_RESULT      NUMBER NULL 
);

ALTER TABLE Job_Seeker
	ADD CONSTRAINT  XPKJob_Seeker PRIMARY KEY (JS_ID);

CREATE TABLE Preparation_for_Turnover
(
	C_NUM                NUMBER NOT NULL ,
	CFD_NUM              NUMBER NULL ,
	P_ID                 NUMBER NOT NULL ,
	NAME                 VARCHAR(18) NULL ,
	COMPANY_EMAIL        VARCHAR(18) NULL ,
	PW                   VARCHAR(18) NULL ,
	CF_NUM               NUMBER NULL ,
	MATCHING_RESULT      NUMBER NULL 
);

ALTER TABLE Preparation_for_Turnover
	ADD CONSTRAINT  XPKPreparation_for_Turnover PRIMARY KEY (P_ID);

CREATE TABLE Worker
(
	C_NUM                NUMBER NOT NULL ,
	CFD_NUM              NUMBER NOT NULL ,
	W_ID                 NUMBER NOT NULL ,
	NAME                 CHAR(18) NULL ,
	EMP_NUM              NUMBER NULL ,
	COMPANY_EMAIL        VARCHAR(18) NULL ,
	PW                   VARCHAR(18) NULL ,
	MATCHING_RESULT      NUMBER NULL ,
	CF_NUM               NUMBER NULL 
);

ALTER TABLE Worker
	ADD CONSTRAINT  XPKWorker PRIMARY KEY (W_ID);

CREATE TABLE SPEC
(
	CERTIFICATION        VARCHAR2(30) NULL ,
	GRADE                FLOAT NULL ,
	INTERNSHIP           VARCHAR2(30) NULL ,
	TOEIC                INTEGER NULL ,
	OPIC                 VARCHAR2(20) NULL ,
	CONTEST              VARCHAR2(30) NULL ,
	AWARDS               VARCHAR2(30) NULL ,
	STUDY_ABROAD         VARCHAR2(30) NULL ,
	VOLUN                VARCHAR2(30) NULL ,
	SPEC_NUM             NUMBER NOT NULL ,
	TOEIC_SPEAKING       INTEGER NULL ,
	P_ID                 NUMBER NULL ,
	W_ID                 NUMBER NULL ,
	JS_ID                NUMBER NULL 
);

ALTER TABLE SPEC
	ADD CONSTRAINT  XPKSPEC PRIMARY KEY (SPEC_NUM);

CREATE TABLE INFO
(
	ANNUAL_INCOME        VARCHAR(18) NULL ,
	DEPARTMENT_MOOD      VARCHAR(18) NULL ,
	JOB_SATISFATION_R    VARCHAR(18) NULL ,
	CAFETERIA            VARCHAR(18) NULL ,
	TRAFFIC_CONVENIENCE  VARCHAR(18) NULL ,
	EMPLOYEE_WELLFARE    VARCHAR(18) NULL ,
	P_ID                 NUMBER NULL ,
	W_ID                 NUMBER NULL ,
	I_NUM                NUMBER NOT NULL ,
	CFD_NUM              NUMBER NULL ,
	JOB_SATISFACTION_H   CHAR(18) NULL 
);

ALTER TABLE INFO
	ADD CONSTRAINT  XPKINFO PRIMARY KEY (I_NUM);

CREATE TABLE recommend_matching_tw
(
	P_ID                 NUMBER NOT NULL ,
	W_ID                 NUMBER NOT NULL 
);

ALTER TABLE recommend_matching_tw
	ADD CONSTRAINT  XPKrecommend_matching_tw PRIMARY KEY (P_ID,W_ID);

CREATE TABLE recommend_matching_jw
(
	W_ID                 NUMBER NOT NULL ,
	JS_ID                NUMBER NOT NULL 
);

ALTER TABLE recommend_matching_jw
	ADD CONSTRAINT  XPKrecommend_matching_jw PRIMARY KEY (W_ID,JS_ID);

CREATE TABLE STATISTIC
(
	ST_NUM               NUMBER NOT NULL ,
	C_NUM                NUMBER NOT NULL ,
	CFD_NUM              NUMBER NULL ,
	ANNUAL_INCOME        VARCHAR2(20) NULL ,
	DEPARTMENT_MOOD      VARCHAR2(20) NULL ,
	JOB_SATISFACTION     VARCHAR2(20) NULL ,
	CAFETERIA            VARCHAR2(20) NULL ,
	TRAFFIC_CONVENIENCE  VARCHAR2(20) NULL ,
	EMPLOYEE_WELLFARE    VARCHAR2(20) NULL 
);

ALTER TABLE STATISTIC
	ADD CONSTRAINT  XPKSTATISTIC PRIMARY KEY (ST_NUM);

CREATE TABLE JS_SCRAP
(
	ST_NUM               NUMBER NOT NULL ,
	JS_ID                NUMBER NOT NULL ,
	S_NUM_JS             NUMBER NOT NULL ,
	SCRAP_DATE           DATE NULL 
);

ALTER TABLE JS_SCRAP
	ADD CONSTRAINT  XPKSCRAP_JS PRIMARY KEY (S_NUM_JS);

CREATE TABLE T_SCRAP
(
	ST_NUM               NUMBER NOT NULL ,
	S_NUM_T              NUMBER NOT NULL ,
	SCRAP_DATE           DATE NULL ,
	P_ID                 NUMBER NOT NULL 
);

ALTER TABLE T_SCRAP
	ADD CONSTRAINT  XPKSCRAP_T PRIMARY KEY (S_NUM_T);

ALTER TABLE DEPARTMENT
	ADD (CONSTRAINT R_39 FOREIGN KEY (CF_NUM) REFERENCES FIELD (CF_NUM));

ALTER TABLE DEPARTMENT
	ADD (CONSTRAINT R_37 FOREIGN KEY (C_NUM) REFERENCES COMPANY (C_NUM) ON DELETE SET NULL);

ALTER TABLE TRUST
	ADD (CONSTRAINT R_80 FOREIGN KEY (CFD_NUM) REFERENCES DEPARTMENT (CFD_NUM));

ALTER TABLE Job_Seeker
	ADD (CONSTRAINT R_88 FOREIGN KEY (CF_NUM) REFERENCES FIELD (CF_NUM) ON DELETE SET NULL);

ALTER TABLE Preparation_for_Turnover
	ADD (CONSTRAINT R_19 FOREIGN KEY (C_NUM) REFERENCES COMPANY (C_NUM));

ALTER TABLE Preparation_for_Turnover
	ADD (CONSTRAINT R_54 FOREIGN KEY (CFD_NUM) REFERENCES DEPARTMENT (CFD_NUM) ON DELETE SET NULL);

ALTER TABLE Preparation_for_Turnover
	ADD (CONSTRAINT R_86 FOREIGN KEY (CF_NUM) REFERENCES FIELD (CF_NUM) ON DELETE SET NULL);

ALTER TABLE Worker
	ADD (CONSTRAINT R_20 FOREIGN KEY (C_NUM) REFERENCES COMPANY (C_NUM));

ALTER TABLE Worker
	ADD (CONSTRAINT R_55 FOREIGN KEY (CFD_NUM) REFERENCES DEPARTMENT (CFD_NUM));

ALTER TABLE Worker
	ADD (CONSTRAINT R_92 FOREIGN KEY (CF_NUM) REFERENCES FIELD (CF_NUM) ON DELETE SET NULL);

ALTER TABLE SPEC
	ADD (CONSTRAINT R_96 FOREIGN KEY (P_ID) REFERENCES Preparation_for_Turnover (P_ID) ON DELETE SET NULL);

ALTER TABLE SPEC
	ADD (CONSTRAINT R_97 FOREIGN KEY (W_ID) REFERENCES Worker (W_ID) ON DELETE SET NULL);

ALTER TABLE SPEC
	ADD (CONSTRAINT R_98 FOREIGN KEY (JS_ID) REFERENCES Job_Seeker (JS_ID) ON DELETE SET NULL);

ALTER TABLE INFO
	ADD (CONSTRAINT R_76 FOREIGN KEY (P_ID) REFERENCES Preparation_for_Turnover (P_ID));

ALTER TABLE INFO
	ADD (CONSTRAINT R_77 FOREIGN KEY (W_ID) REFERENCES Worker (W_ID));

ALTER TABLE recommend_matching_tw
	ADD (CONSTRAINT R_99 FOREIGN KEY (P_ID) REFERENCES Preparation_for_Turnover (P_ID));

ALTER TABLE recommend_matching_tw
	ADD (CONSTRAINT R_100 FOREIGN KEY (W_ID) REFERENCES Worker (W_ID));

ALTER TABLE recommend_matching_jw
	ADD (CONSTRAINT R_101 FOREIGN KEY (W_ID) REFERENCES Worker (W_ID));

ALTER TABLE recommend_matching_jw
	ADD (CONSTRAINT R_102 FOREIGN KEY (JS_ID) REFERENCES Job_Seeker (JS_ID));

ALTER TABLE STATISTIC
	ADD (CONSTRAINT R_83 FOREIGN KEY (CFD_NUM) REFERENCES DEPARTMENT (CFD_NUM) ON DELETE SET NULL);

ALTER TABLE STATISTIC
	ADD (CONSTRAINT R_82 FOREIGN KEY (C_NUM) REFERENCES COMPANY (C_NUM));

ALTER TABLE JS_SCRAP
	ADD (CONSTRAINT R_30 FOREIGN KEY (ST_NUM) REFERENCES STATISTIC (ST_NUM));

ALTER TABLE JS_SCRAP
	ADD (CONSTRAINT R_31 FOREIGN KEY (JS_ID) REFERENCES Job_Seeker (JS_ID));

ALTER TABLE T_SCRAP
	ADD (CONSTRAINT R_34 FOREIGN KEY (ST_NUM) REFERENCES STATISTIC (ST_NUM));

ALTER TABLE T_SCRAP
	ADD (CONSTRAINT R_1113 FOREIGN KEY (P_ID) REFERENCES Preparation_for_Turnover (P_ID));
